window.CASES_DEMO_DATA = {
  schemaVersion: 1,
  statuses: {
    new: "新規問い合わせ",
    selecting: "施工店選定中",
    introduced: "紹介済み",
    awaiting_response: "施工店回答待ち",
    site_visit_scheduled: "現調予定",
    estimate_submitted: "見積提出済み",
    contracted: "成約",
    lost: "失注",
    declined: "辞退",
    completed: "完了"
  },
  workCategories: ["カーポート", "フェンス", "門扉", "ウッドデッキ", "テラス", "物置", "土間コンクリート", "ブロック工事", "アプローチ", "外構一式", "リフォーム外構", "その他"],
  cases: [
    {
      caseId: "EXK-2026-001",
      createdAt: "2026-08-24T09:30:00+09:00",
      customerName: "デモ顧客A",
      customerContact: "demo-a@example.invalid",
      area: "高松市西部",
      initialRequestCategories: ["カーポート"],
      requestSummary: "既存駐車場へ2台用カーポートの新設を検討。現地の勾配確認が必要です。",
      preferredTiming: "1〜3か月以内",
      assignedContractorId: "DEMO-CONTRACTOR-01",
      assignedContractorName: "デモ外構",
      status: "site_visit_scheduled",
      siteVisitDate: "2026-09-06T10:00:00+09:00",
      estimateSubmittedAt: null,
      contractStatus: "pending",
      finalWorkCategories: [],
      finalContractAmount: null,
      referralFee: null,
      reportSubmittedAt: null,
      notes: "前面道路が狭いため、搬入方法を現調時に確認してください。",
      declinedContractorIds: [],
      lastStatusUpdatedAt: "2026-08-29T14:00:00+09:00"
    },
    {
      caseId: "EXK-2026-002",
      createdAt: "2026-08-18T15:10:00+09:00",
      customerName: "デモ顧客B",
      customerContact: "demo-b@example.invalid",
      area: "丸亀市周辺",
      initialRequestCategories: ["フェンス", "門扉"],
      requestSummary: "道路側の目隠しフェンスと門扉交換について相談。商品は未定です。",
      preferredTiming: "時期未定",
      assignedContractorId: "DEMO-CONTRACTOR-01",
      assignedContractorName: "デモ外構",
      status: "estimate_submitted",
      siteVisitDate: "2026-08-23T13:00:00+09:00",
      estimateSubmittedAt: "2026-08-26T17:20:00+09:00",
      contractStatus: "pending",
      finalWorkCategories: [],
      finalContractAmount: null,
      referralFee: null,
      reportSubmittedAt: null,
      notes: "既存ブロックの状態を確認済み。見積回答待ちです。",
      matchingCategories: ["フェンス", "土間コンクリート"],
      declinedContractorIds: [],
      lastStatusUpdatedAt: "2026-08-26T17:20:00+09:00"
    },
    {
      caseId: "EXK-2026-003",
      createdAt: "2026-07-29T11:40:00+09:00",
      customerName: "デモ顧客C",
      customerContact: "demo-c@example.invalid",
      area: "坂出市周辺",
      initialRequestCategories: ["物置"],
      requestSummary: "庭への物置設置。基礎工事を含めた提案を希望しています。",
      preferredTiming: "できるだけ早く",
      assignedContractorId: "DEMO-CONTRACTOR-02",
      assignedContractorName: "サンプル施工店",
      status: "contracted",
      siteVisitDate: "2026-08-02T09:00:00+09:00",
      estimateSubmittedAt: "2026-08-04T16:00:00+09:00",
      contractStatus: "contracted",
      finalWorkCategories: ["物置", "土間コンクリート"],
      finalContractAmount: 480000,
      referralFee: null,
      reportSubmittedAt: "2026-08-09T12:30:00+09:00",
      notes: "初回商談内で土間コンクリート工事を追加。",
      declinedContractorIds: [],
      lastStatusUpdatedAt: "2026-08-09T12:30:00+09:00"
    }
  ]
};
